### ISSUE TITLE
not seeing my config getting set up via Docker Compose for v0.13 container

### ISSUE THREAD

**Issue by jstoner** [influxdata/influxdb-docker#12]
I am creating an InfluxDB container using Docker Compose. I invoke compose thus:

`docker-compose docker-compose.prod.yml up tsdb`

my docker-compose.prod.yml:

```
version: '2'
services:

  tsdata:
    image: influxdb:0.13
    volumes:
      - /var/lib/influxdb
    command: "true"

  tsdb:
    image: influxdb:0.13
    restart: always
    environment:
      - INFLUXDB_META_DIR = "/var/lib/influxdb/meta"
      - INFLUXDB_DATA_DIR = "/var/lib/influxdb/data"
      - INFLUXDB_DATA_WAL_DIR = "/var/lib/influxdb/wal"
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_BIND_ADDRESS = ":8083"
      - INFLUXDB_ADMIN_HTTPS_ENABLED = true
      - INFLUXDB_ADMIN_HTTPS_CERTIFICATE = "/etc/ssl/certs/blah.pem"
      - INFLUXDB_HTTP_AUTH = true
      - INFLUXDB_HTTPS_ENABLED = true
      - INFLUXDB_HTTPS_CERTIFICATE = "/etc/ssl/certs/blah.pem"
    volumes_from:
      - tsdata
    ports:
      - "blah:8083"
      - "blah:8086"
```

and this is my resulting influx.conf:

```
[ jstoner@erzulie:~/forelight/task ] develop
2072s 👍  $> docker-compose run --rm tsdb /bin/bash
root@1ed4f991ef43:/# cat /etc/influxdb/influxdb.conf
[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
```

when I hit the web addresses they don't respond to https but they do respond to http.

I am a noob with both Docker and InfluxDB. I'm just trying to follow the practices that have been recommended to me.

**Comment by jsternberg** [comment]
I don't know if you can have spaces inside of the environment declarations so you can try removing those. You can also try using dictionary syntax like from here: https://docs.docker.com/compose/compose-file/#environment

None of the environment variables will modify the on-disk configuration file. Are there any messages in the log file with `[admin]`?

**Comment by jstoner** [comment]
Oh, and it appears that when the admin interface looks for the query endpoint, it looks at the port in influxdb.conf. Which seems to break if you use Docker to map to a different port--it goes to the docker host port, not the container port. Looks like you have to set the port you want in the Influxdb config and then map same:same in Docker. (Maybe Docker networking would provide some other way, but I haven't gotten that far.)

You might want to make a note in the documentation on Docker Hub, someone even noobier than me will get confused.

**Comment by jstoner** [comment]
That appears to have done it, thanks! Way to fail silently, Docker. Grr.

**Comment by jstoner** [comment]
Okay, crap. After wrangling with Docker and some other stuff, now I see some strange things.

Here's my current stanza:

```
  tsdb:
    build:
      context: ./tsdb_prod
    restart: always
    environment:
      - INFLUXDB_META_DIR="/var/lib/influxdb/meta"
      - INFLUXDB_DATA_DIR="/var/lib/influxdb/data"
      - INFLUXDB_DATA_WAL_DIR="/var/lib/influxdb/wal"
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_BIND_ADDRESS=":6789"
      - INFLUXDB_HTTP_BIND_ADDRESS=":4567"
      - INFLUXDB_ADMIN_HTTPS_ENABLED=true
      - INFLUXDB_ADMIN_HTTPS_CERTIFICATE="/etc/ssl/certs/blah.pem"
      - INFLUXDB_HTTP_AUTH=true
      - INFLUXDB_HTTPS_ENABLED=true
      - INFLUXDB_HTTPS_CERTIFICATE="/etc/ssl/certs/blah.pem"
    volumes_from:
      - tsdata
    ports:
      - "4567:4567"
      - "6789:6789"
```

Still not accepting https traffic. http yes, https, no.

I see my admin interface on the http port, and no response on the other one. 
I have the
